name: Auto Brancher

on:
  issues:
    types: [opened]

jobs:

  branch:
    runs-on: ubuntu-latest
      steps:

        # Set environment vairables to allow configuration
        - name: Set env
          run: |
            echo "GITHUB_NEW_BRANCH=$(echo ${{ github.event.issue.number }} ${{ github.event.issue.title }} | tr -Cs '[:alnum:]\n' '-' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        # Create new branch and push to remote
        - uses: actions/checkout@v2
          with:
            ref: main
        - name: Auto branch
          run: |
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/yuri-norwood/going-gophers.git
            git checkout -b "${{ env.GITHUB_NEW_BRANCH }}"
            git push -u origin "${{ env.GITHUB_NEW_BRANCH }}"
